### ISSUE TITLE
Crash bad_alloc when trying to load CSL models in config wizard

### ISSUE THREAD

**Issue by kellpossible** [swift-project/pilotclient#108]
Operating System: Archlinux 64 bit
Simulator: X-Plane

Model directory: `/home/luke/.local/share/Steam/steamapps/common/X-Plane 11/Custom Data/CSL/` with BB model set inside `BB` directory.

Screen recording:
![swift-client-crash](https://user-images.githubusercontent.com/4527338/118048173-01d15e80-b3d0-11eb-8e5a-53183c7b4d35.gif)

gdb output:

```txt
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Thread 71 "Model loader fo" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fff8ffff640 (LWP 1413096)]
0x00007ffff3423ef5 in raise () from /usr/lib/libc.so.6
```

**Comment by oktal3700** [comment]
How much RAM do you have available, and can you see how much is being used by the wizard when it crashes?

Please could you produce a core dump with gdb's [`gdump` command](https://sourceware.org/gdb/current/onlinedocs/gdb/Core-File-Generation.html) after the crash and upload it here.

**Comment by kellpossible** [comment]
I'll check that soon. From memory I should have about 10 GB available.

**Comment by ltoenning** [comment]
Does this still happen?

**Comment by kellpossible** [comment]
No idea we could close for now
