### ISSUE TITLE
[Radar] Option to display all aircraft or mode C only

### ISSUE THREAD

**Issue by oktal3700** [swift-project/pilotclient#109]

**Comment by esramos-design** [comment]
Hello, just copy the started conversation i made about

Got another request for the radar please, i just got noticed today's flight.
I was flying in formation for the Abbotsford Airshow in Canada, CYXX, Center and AAP was online and realised when you flying in formation, you are requested to your wingman to squawk "std-by" and the lider in "charly", so...
when he was sqk "std-by", i could not see him at all, stealth.
Is there  a way to add an option to be able to see std-by aircraft on radar??

**Comment by oktal3700** [comment]
I have checked the source code. Aircraft squawking standby should already be displayed on swift's radar. If not, then that is a bug, and I do not understand how it could happen.

**Comment by esramos-design** [comment]
Thank you, my friend,

I’ll do more test and identify precisely when it happens, I’ll let you know

 

Kind Regards,

 

E. S. Ramos
Chairman of the Military Committee CMC
COM AIRCOM - NATO1 (Admin - Founder) ***@***.*** Tweet me @VirtualNATO        FACEBOOK: virtualnato       INSTAGRAM:  VirtualNATO VirtualNATO.org is in NO WAY affiliated with NATO.int or or any real world NATO organization / companies, therefore, WE are a stand-alone non-profit virtual organization of flight simulation enthusiast, a group of friends with the common interest in promoting enjoyment and education through the simulation of military operations and procedure through the use of operating standards within several flight simulation platforms, like VATSIM, IVAO and future POSCON.

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

From: oktal3700 ***@***.***>
Reply to: swift-project/pilotclient ***@***.***>
Date: Thursday, 22 July 2021 at 19:41
To: swift-project/pilotclient ***@***.***>
Cc: esramos-design ***@***.***>, Manual ***@***.***>
Subject: Re: [swift-project/pilotclient] [Radar] Option to display all aircraft or mode C only (#109)

 

I have checked the source code. Aircraft squawking standby should already be displayed on swift's radar. If not, then that is a bug, and I do not understand how it could happen.

**Comment by ltoenning** [comment]
Any news on this? Otherwise, I would close the issue.

IIRC, all aircraft are always displayed on the radar.  I find this quite useful, especially in some ground-situations without having a separate moving map running.
