### ISSUE TITLE
Warning message dialog when connecting as OBS

### ISSUE THREAD

**Issue by oktal3700** [swift-project/pilotclient#122]
If no sim plugin is loaded then swift will default to connecting to the network as Observer. For most users this is unexpected and confusing. There was probably some problem with their sim, but the client's behavior makes them think the problem is with the network or the model matching.

When connecting with no sim plugin loaded, there should be an "are you sure?" dialog box to confirm the user's intent.

**Comment by ltoenning** [comment]
This is fixed in the latest pre-release available to our testers.
