### ISSUE TITLE
Support ICAO equipment code in flight plan

### ISSUE THREAD

**Issue by oktal3700** [swift-project/pilotclient#124]
Vatsim allows ICAO equipment codes now which are much more complex than the single-character FAA equipment codes. Andreas helpfully provided a good document explaining the codes ("Item 10").
[FPL-02.pdf](https://github.com/swift-project/pilotclient/files/7421332/FPL-02.pdf)
[FPL-03.pdf](https://github.com/swift-project/pilotclient/files/7421333/FPL-03.pdf)

**Comment by ltoenning** [comment]
For the record:

ICAO equipment codes are enabled on VATSIM servers with the ``ICAOEQ`` capability. When enabled, the ``m_aircraftIcaoType`` member inside the FSD flightplan message should contain an ICAO equipment code of the format ``(Aircraft ICAO)/(Wake Turbulence Category)-(NAV/COM Equipment)/(SSR Equipment)`` (for example ``A20N/M-SDE2E3FGHIJ1RWXY/LB1``).
