### ISSUE TITLE
Aircraft Type Not Visible for ATC

### ISSUE THREAD

**Issue by AirLuSa** [swift-project/pilotclient#126]
When checking Heavy or TCAS in the flightplan the Aircrafttype is not going to reported to ATC. When looking on VatScope there is a ? In the aircraft type section. 
It works fine when non of the check boxes are checked.

**Comment by oktal3700** [comment]
Thanks for the report. Which version are you using?

**Comment by AirLuSa** [comment]
version 0.9.7.149

**Comment by ltoenning** [comment]
Starting with the next version, swift will support ICAO equipment codes (https://github.com/swift-project/pilotclient/issues/124). Hence, the TCAS and Heavy checkboxes were removed and this issue will not be investigated/fixed anymore.
