### ISSUE TITLE
Adjust own frequency by up to 5 kHz to match the controller's

### ISSUE THREAD

**Issue by oktal3700** [swift-project/pilotclient#128]
From Mike Evans on the Vatsim development discord:
> So it looks like swift is transmitting on 131.570 instead of 131.575
> and the controller isn't able to receive text comms from that pilot..
> the pilot is tuned to 131.575 in their plane
> and can receive text messages from the controller, but when they go to reply, the controller doesn't see the response.

And from Collin Koldoff:
> More recently facilities have been shifting away from dropping the 5, most facilities that do tx/rx on both frequencies per their SOP

**Comment by ltoenning** [comment]
Fix released with alpha version 0.12.48.
