### ISSUE TITLE
Airline logos not displayed anymore since 0.9.7.x

### ISSUE THREAD

**Issue by FlyingFoxVATSIM** [swift-project/pilotclient#133]
After change from swift 0.9.6.x to 0.9.7.x, airline logos are not displayed anymore, e.g. on the Aircraft widget.

**Comment by oktal3700** [comment]
This is intentional, as the existence of this feature made it impossible to deal with the overall complexity of the software. The feature can be restored in the far future when the complexity has been dealt with.
