### ISSUE TITLE
[Linux] crash when exiting swiftgui

### ISSUE THREAD

**Issue by oktal3700** [swift-project/pilotclient#134]
https://discord.com/channels/539048679160676382/569861511724531712/912788861854294036
> swiftlauncher still exits with a core dump on Linux (newest version 0.9.6.91). Nothing major, just a non-nice exit.

**Comment by ltoenning** [comment]
I asked the author: The core dump happens when exiting swiftgui.

**Comment by ltoenning** [comment]
Fixed with 0.11
