### ISSUE TITLE
X-Plane (Linux) crashes when XSwiftBus loads with Vulkan shaders enabled

### ISSUE THREAD

**Issue by jonaseberle** [swift-project/pilotclient#137]
I tested with these XSwiftBus versions:

Alpha version 0.9.8.38
Beta version 0.9.7.166
Beta version 0.9.6.98
Beta version 0.9.4.389

Loading X-Plane with Vulkan shaders without the plugin `Resources/plugins/xswiftbus` works.

I've set in `Resources/plugins/xswiftbus/xswiftbus.conf`:
```
# Render phase debugging - to help diagnose crashes
debug = on

# TCAS traffic - to disable in case of crashes
tcas = off
```

X-Plane Log.txt (I can't see anything interesting unfortunately)
https://gist.github.com/jonaseberle/bd1a472b05460ad7da8276f2b2c3c9e0

This is the last thing seen before X-Plane crashes:
![image](https://user-images.githubusercontent.com/1678001/146673839-797e5f2f-d5d3-48e6-b4c4-90251eb23966.png)

**Comment by oktal3700** [comment]
Make sure you have the latest graphics drivers available for your distro.

It's my understanding that Intel graphics are poorly supported by X-Plane on Linux. See https://www.x-plane.com/kb/updating-graphics-drivers-for-vulkan-metal/

**Comment by jonaseberle** [comment]
From that page: `Intel systems aren’t currently supported because their driver lacks required functionality` oh, interesting. 
Well, nevermind, I'll switch to another PC anyways. Selecting Vulkan hasn't given me more FPS anyways.
