### ISSUE TITLE
[Swift 0.10.11] No other Aircraft are shown

### ISSUE THREAD

**Issue by AirLuSa** [swift-project/pilotclient#141]
When using Swift 0.10.11 for VATSIM velocity and connecting to the vatsim velocity server, no other aircraft are shown, although the model set is correctly installed. Voice is working normal.

**Comment by AirLuSa** [comment]
using on Mac Os

**Comment by oktal3700** [comment]
Already known and we are not using GitHub issues for velocity test feedback.
