### ISSUE TITLE
swift gui thinks I am connected to vatsim despite connection error 

### ISSUE THREAD

**Issue by tigert** [swift-project/pilotclient#149]
So this is related to the velocity switch, I installed 0.11.0 and of course it does not (yet) work as the network has not switched to velocity infrastructure yet, and Swift gives me a connection error as expected.

However after cosing the error message, the GUI appears as if the connection was successful: The "Connect" button on the window turns green and shows "Connected", and has a "Disconnect" button.

**Comment by ltoenning** [comment]
Maybe this happened if the TCP socket wasn't disconnected when using the wrong VATSIM protocol version.

As Velocity is live since quite some time, I will close this issue for now.
If the same issue happens in some other constellation, feel free to reopen the issue.
