### ISSUE TITLE
Error connecting to flightgear

### ISSUE THREAD

**Issue by TAM4277** [swift-project/pilotclient#153]
When I connect to flightgear, the following error occurs: This version of swift is not compatible with this Flightgear version. For further information check http://wiki.flightgear.org/Swift.

This problem started after updating vatsim servers on monday. I updated to the latest version and the problem persists.
![error](https://user-images.githubusercontent.com/63882517/152240527-d5876c6e-f990-46c0-9230-445a1fec6496.jpg)

**Comment by ltoenning** [comment]
Which Flightgear version are you using?

FG 2020.3.* (LTS) and earlier isn't compatible with swift >= 0.11.0.
The only way  to use swift with VATSIM and Flightgear is by using the nightlies or building from next right now.

**Comment by TAM4277** [comment]
Roger, tanks!!!!!

Em qua., 2 de fev. de 2022 às 19:07, Lars Toenning ***@***.***>
escreveu:
