### ISSUE TITLE
Update checker downloads older XSwiftBus

### ISSUE THREAD

**Issue by droesen** [swift-project/pilotclient#154]
![image](https://user-images.githubusercontent.com/63562075/152634614-f4ab1914-0e9d-481f-b3f9-63ef5c8544e4.png)

but clicking on "download" next to XSwiftBus, we'll get 0.11.7:

![image](https://user-images.githubusercontent.com/63562075/152634645-3a213970-d991-4fc4-bab1-f4712b53bf23.png)

The same already happened 0.11.0 -> 0.11.7

**Comment by oktal3700** [comment]
Will be fixed after the next update. Thank you very much for the report.
