### ISSUE TITLE
Request configurable network connect/disconnect notification sound

### ISSUE THREAD

**Issue by FlyingFoxVATSIM** [swift-project/pilotclient#156]
Could we add a configurable sound for when users connect/disconnect from the network server?

Also, we can probably remove the sound events "no audio transmission warning", "ATC frequency selected" and "ATC frequency deselected".

**Comment by ltoenning** [comment]
> Could we add a configurable sound for when users connect/disconnect from the network server?

You mean when the swift user connects itself or if other users "appear" in the vicinity? The first case should already work with the ``login.wav`` and ``logoff.wav`` files, shouldn't it?

> Also, we can probably remove the sound events "no audio transmission warning", "ATC frequency selected" and "ATC frequency deselected".

I agree on the "no audio transmission warning". This is not used anymore.
"ATC frequency selected" and "ATC frequency deselected" is still used in the code. Aren't these notification sounds not working (anymore)?

**Comment by ltoenning** [comment]
> However, does anyone use them?

Maybe not very common. I am fine with removing these two options as well.

> Re the connect/disconnect sounds: we actually do have something already, login.wav and logoff.wav. My idea was to have an option to configure them, but I guess users should just replace those files with their custom wav-files, as we do with the other sound files.

I would prefer a single method for customizing notification sounds. Adding another method only complicates things.

**Comment by FlyingFoxVATSIM** [comment]
I do agree, but then we'd have to add them to the Audio page of swiftGUI.
