### ISSUE TITLE
MSFS not listed in aircraft models list in the documentation

### ISSUE THREAD

**Issue by FX5F** [swift-project/pilotclient#167]
At the page https://docs.swift-project.org/doku.php?id=download_aircraft_models, MSFS is not listed in the list in the main screen. But it's listed on the left in the menu.

Expectation: It should also be listed in the main list

**Comment by FX5F** [comment]
Another minor error:
https://docs.swift-project.org/doku.php?id=msfs_configuration

`A model set consists of AI (Artificial Intelligence) aircraft that have to be installed on your computer somewhere inside the X-Plane folder`
It says X-Plane, but should MSFS.

**Comment by FlyingFoxVATSIM** [comment]
> Another minor error: https://docs.swift-project.org/doku.php?id=msfs_configuration
> 
> `A model set consists of AI (Artificial Intelligence) aircraft that have to be installed on your computer somewhere inside the X-Plane folder` It says X-Plane, but should MSFS.

Thanks for pointing out those two things, I have corrected them now. If you find more, feel free to let us know!
