### ISSUE TITLE
Notification sound for UNICOM messages does not play

### ISSUE THREAD

**Issue by FlyingFoxVATSIM** [swift-project/pilotclient#168]
swift 0.12.35 - 32bit
FS9

I have a dedicated folder called "swift custom sounds" where all my custom notification sound files are stored. As suggested by you, one of them is called **unicommessage.wav**. I added the same file to both **swift-0.12-32bit\share\sounds** and my custom path.
On the "Audio" page I successfully tested the notification sound by selecting and deselecting UNICOM message notifications. But when connected to VATSIM, no sound is played when other players send messages on UNICOM 122.800.

**Comment by ltoenning** [comment]
The "Text message on ATC frequency" and "Text message on UNICOM" sounds are both not triggered when receiving such messages.
Should be an easy fix.

**Comment by ltoenning** [comment]
Fixed and released with alpha version 0.12.48.
