### ISSUE TITLE
Swap the FRQ column with DISTANCE

### ISSUE THREAD

**Issue by esramos-design** [swift-project/pilotclient#173]
https://media.discordapp.net/attachments/539846348275449887/1029383726536335431/unknown.png

I have a request, can we swap the FRQ column with DISTANCE?, is it possible?
When we have a huge list of ATC and told to contact one, i always mix the numbers

**Comment by ltoenning** [comment]
Simply changing the order would be an easy change. But the order might be subjective to the user.
But I also agree that the frequency is more important than the (exact) distance and should perhaps be listed before the distance.

It seems that the column order cannot be customized by user right now.

@oktal3700 What do you think?

**Comment by oktal3700** [comment]
@ltoenning agreed on all points
