### ISSUE TITLE
FSX selector grayed out in 64-bit build configuration wizard (required for MSFS)

### ISSUE THREAD

**Issue by ajungren** [swift-project/pilotclient#178]
On the [swift download wiki page](https://docs.swift-project.org/doku.php?id=download_swift_installer) MSFS is incorrectly listed as compatible with both the 32-bit and 64-bit builds but only the 32-bit build is supported.

**Comment by ltoenning** [comment]
It should work with 32bit and 64bit. Only older 64bit versions of swift do not support MSFS.

Can you make sure, that the MSFS plugin is activated as described here: https://docs.swift-project.org/doku.php?id=msfs_configuration#msfs_activation.

**Comment by ajungren** [comment]
I selected MSFS during the setup...

![swift1](https://user-images.githubusercontent.com/520443/209482562-b84e53f4-c6a8-4fdc-8b48-6b1963673644.png)

...but the FSX checkbox is disabled in the configuration wizard.

![swift2](https://user-images.githubusercontent.com/520443/209482574-296de8d6-d4e8-456a-809c-889cf20ed8b1.png)

**Comment by ltoenning** [comment]
Okay, that is indeed not correct. Thanks for reporting. But for now you should be able to set the paths later within the mapping tool (swiftdata). There you should be able to select FSX.



@oktal3700 The check is done here https://github.com/swift-project/pilotclient/blob/2ed20070486afdc8018222731ad08da4c10fef97/src/blackgui/components/configsimulatorcomponent.cpp#L75
Should we remove this check entirely for now to avoid confusion until the full MSFS integration is finished? The check if the version is compiled with a simulator support is not checked in other places either and does not depend on the installed plugins.

**Comment by oktal3700** [comment]
@ltoenning I don't know it well enough to answer. If it looks good to you then go ahead.

**Comment by ajungren** [comment]
Thanks for getting on this so quickly, I figured I’d finally give VATSIM a shot while I’m trapped in my house.

I’m obviously super unfamiliar with the code base, but I created a PR that, at least for me, makes it work as expected if I understood correctly though like I said in the PR I need to test it more tomorrow and make sure it doesn’t break anything else.

**Comment by ltoenning** [comment]
The upcoming release will support MSFS natively. This is no longer required.
