### ISSUE TITLE
Enable FSD METAR command

### ISSUE THREAD

**Issue by Sora012** [swift-project/pilotclient#181]
I'm requesting a feature to handle the METAR command for private FSD's instead of having to use "Real Weather" profile.

**Comment by ltoenning** [comment]
swift currently does not use the ``$AR`` and ``$AX`` FSD messages to fetch METARs.

@Sora012 What do you want to achieve with using the METARS from FSD? Only display them within swift or use them to inject weather into the simulator? As you are talking about the "Real Weather" profile, I assume you are talking about the latter.

For this, different (more) information is required than what is provided by a METAR as a METAR only contains information about the weather around an airport. However, the weather system also requires information about temperature, clouds and especially winds at higher altitudes. For this, swift uses the [GRIB2 format](https://en.wikipedia.org/wiki/GRIB) which basically contains a three-dimensional grid with weather information at the grid points.

**Comment by ltoenning** [comment]
``#WX`` also seem to be used for METARs by some FSD servers.

**Comment by Sora012** [comment]
I'm rather unfamiliar with how it all works to be honest. I originally cloned a FSD for local multiplayer with X-Plane 12 as this seems to be the only client left with FSD capability and so I started working on the FSD and got the METAR stuff working again which is the reason I originally submitted this issue as I wanted to get weather working in-game. As it was never using the METAR information that I could tell (at the time) to actually update weather. I was mainly interested in getting weather working locally from the FSD when I created this issue, instead of relying on additional functionality like "Real Weather" option from the client.

If its not feasible I could just rip out the METAR information from the FSD I cloned. Thanks for the reply!

**Comment by ltoenning** [comment]
Adding this makes it more complicated on our side (as there is no single definition how the METAR is transmitted via FSD) and as mentioned before it would not lead to realistic weather results except around an airport.

As we are also thinking about removing the swift weather engine from swift itself (maybe putting it in a standalone executable) we will rather not implement this.
