### ISSUE TITLE
XP12 Incorrect altitude

### ISSUE THREAD

**Issue by piperpilot99** [swift-project/pilotclient#182]
I understand that the altitude reporting in XP12 has changed and that there is a new version of Swift to account for this.

It doesn't seem to be available yet. Does anyone know where I can download this from?

I know that this has been discussed before in several XPlane related forums including here but I haven't been able to find an answer yet.

**Comment by ltoenning** [comment]
We are working on it with #169. But there is no public version with this fix available yet.
Once it is available, we will notify the users via discord with a changelog or you can monitor the Github release page [1].

[1] https://github.com/swift-project/pilotclient/releases
