### ISSUE TITLE
Cannot run swiftlauncher

### ISSUE THREAD

**Issue by Kofi611** [swift-project/pilotclient#204]
I am getting this error while trying to install swift for the first time.

`error while loading shared libraries: libpulse-mainloop-glib.so.0: cannot open shared object file: No such file or directory`

I am on a Chromebook installing via linux for flightgear.

**Comment by ltoenning** [comment]
I am not familiar with ChromeOS but it seems one can "enable" Linux and use apt to install packages, right?
You could try to install that missing library through apt if that is possible and does not conflict with other packages or ChromeOS features.

**Comment by Kofi611** [comment]
@ltoenning 
I tried but apt doesn't recognize the package

**Comment by ltoenning** [comment]
Does this issue still persists? The apt package may be named ``libpulse-mainloop-glib0``.

**Comment by ltoenning** [comment]
One month of inactivity. If the problem still persists and is not solved by installing ``libpulse-mainloop-glib0``, feel free to reopen the issue.
