### ISSUE TITLE
Does pressure pull correctly?

### ISSUE THREAD

**Issue by krisbee** [swift-project/pilotclient#218]
I was flying and I used the weather function - it seemed to pull winds/clouds correctly, but pressure was off from location.  Not sure where it pulls from, but it would be nice if it pulled from VATSIM or METARS and then the pressure would match ATIS or real-life maps.  Not a big deal, since you can look at the window to see the pressure that is being injected into the sim, but would be nice if it matched.  Temp seemed to match.

**Comment by ltoenning** [comment]
The next version of swift will not include the weather plugin anymore.
