### ISSUE TITLE
Move some parts of "programming knowhow" into "developer documentation"

### ISSUE THREAD

**Issue by oktal3700** [swift-project/pilotclient#223]
The Sphinx layout is already much easier to navigate than the Phabricator wiki. But the migration of the wiki has migrated not only the content but also unavoidably retained some of the problems of the wiki. In many places, information about single topics is spread into multiple documents, often with cyclical links between them, so that it is hard for a user to know where to start, when they want to learn about a specific topic.

A great next step would be to clean up the "programming knowhow" section. This section was not supposed to contain anything specific to swift. It was supposed to be a knowledge-base of C++ wisdom and collection of relevant domain-specific information.

For example,

- Idiosyncrasies of C++, but not swift's C++ coding standards.
- FSD protocol spec, but not swift's FSD implementation.
- Useful `git` commands, but not swift's git workflow policy.
- How to compile code on Windows, but not how to compile swift on Windows.
- Explaining the differences between height, altitude, elevation, and flight level in aviation, but not the corresponding C++ classes in swift code.
- Simulator plugin SDK documentation, but not how swift interacts with simulators.
- Description of ICAO aircraft type codes, but not swift-specific peculiarities of model matching.

Anything swift-specific should be moved to "developer documentation".

**Comment by ltoenning** [comment]
@oktal3700 Is this still up-to-date?
