### ISSUE TITLE
AFV: remove voice1.vatsim.uk URL

### ISSUE THREAD

**Issue by oktal3700** [swift-project/pilotclient#255]
[Mike Evans on VATSIM dev discord](https://discord.com/channels/775552633918062643/775736423319732256/1200891334760874095):
> everyone please check that you're using `voice1.vatsim.net` in anything that has AFV built in..  If you're using `voice1.vatsim.uk` you need to change that.

**Comment by ltoenning** [comment]
I already did this on a separate branch: https://github.com/swift-project/pilotclient/commit/5263c0fd9023a240bc7f7f5d06ec9bc30abac6eb

I will submit a pull request soon.
