### ISSUE TITLE
Advice on joystick data causing crashes at startup

### ISSUE THREAD

**Issue by Tony-without-H2O** [swift-project/pilotclient#267]
Due to the crash when I plug in the stick, I have been unable to access swift during takeoff and landing many times recently, but the fact is that I almost never bind the stick to the shortcut key in swift, so can we choose to let swift not access the stick to avoid this situation?
I hope the author can give a similar solution soon, which is very important to me.

**Comment by ltoenning** [comment]
This is the same issue as https://github.com/swift-project/pilotclient/issues/267 right?

**Comment by Tony-without-H2O** [comment]
> This is the same issue as #234 right?

Yes. But I just want to give you an opinion to solve the problem

**Comment by ltoenning** [comment]
Unfortunately we have not found time to look into this issue so far.
To keep all information focused at one point, I added your comment to #234 and I will close this issue.
