### ISSUE TITLE
Where can we find the xswiftbus download?

### ISSUE THREAD

**Issue by phlplowe9** [swift-project/pilotclient#277]
https://datastore.swift-project.org/artifacts/xswiftbus-fat-allos-0.13.18.7z

is giving me a not found error.

I can't download it using the swift client config wizard either.

"No download URL for file name ''"

**Comment by birdydma** [comment]
https://github.com/swift-project/pilotclient/releases

You should install [Alpha version 0.14.36](https://github.com/swift-project/pilotclient/releases/tag/v0.14.36)

DOC is here: https://swift-project.org/

About support, join the Discord server of swift: https://swift-project.org/home/contact/

**Comment by ltoenning** [comment]
I just tested downloading and installing xswiftbus through the config wizard with 0.13.18. It worked without issues.

Did upgrading to the latest alpha version fixed your issue?

**Comment by phlplowe9** [comment]
Oh found it here
https://github.com/swift-project/pilotclient/releases/download/v0.13.18/xswiftbus-fat-allos-0.13.18.7z
