### ISSUE TITLE
Cmake error: no default for CMAKE_BUILD_TYPE 

### ISSUE THREAD

**Issue by talkingerbil** [swift-project/pilotclient#286]
Built on linux just now. First attempt fails with:

> Make Error at CMakeLists.txt:126 (if):
>   if given arguments:
>     "UNIX" "AND" "NOT" "APPLE" "AND" "STREQUAL" "Debug"
>   Unknown arguments specified

Turns out CMAKE_BUILD_TYPE isn't set by default. Maybe set something in the cmake file or add in `-DCMAKE_BUILD_TYPE=Release` to the example command on the wiki page?

https://github.com/swift-project/pilotclient/wiki/Build:-Build

**Comment by ltoenning** [comment]
Thanks for reporting. I will add a default ``CMAKE_BUILD_TYPE`` soon.
