### ISSUE TITLE
Crash after upgrading to macOS Sequoia 15.0

### ISSUE THREAD

**Issue by nola504-4now** [swift-project/pilotclient#299]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               swiftguistd [5563]
Path:                  /Applications/swift-0.14-64bit/*/swiftguistd.app/Contents/MacOS/swiftguistd
Identifier:            org.swift-project.swiftguistd
Version:               0.14.36 (0.14.36)
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-09-30 13:52:10.4537 -0500
OS Version:            macOS 15.0 (24A335)
Report Version:        12
Anonymous UUID:        9C073E0A-4653-13D6-BF1B-003FBE1D6BA0

Time Awake Since Boot: 20000 seconds

System Integrity Protection: enabled

Notes:
PC register does not match crashing frame (0x0 vs 0x11189BE40)

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000008
Exception Codes:       0x0000000000000001, 0x0000000000000008

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [5563]

VM Region Info: 0x8 is not in any region.  Bytes before following region: 4365639672
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      104366000-10438e000    [  160K] r-x/r-x SM=COW  /Applications/swift-0.14-64bit/*/swiftguistd.app/Contents/MacOS/swiftguistd

Error Formulating Crash Report:
PC register does not match crashing frame (0x0 vs 0x11189BE40)

**Comment by nola504-4now** [comment]
Is there an informational site that indicates when it's OK to upgrade Mac OS from a compatibility standpoint?

**Comment by ltoenning** [comment]
This was already reported on our Discord. Something seems to have changed with the fonts on macOS 15. You can bypass the crash by doing the following:

* Open Finder
* Go to ``Applications`` and open the folder swift folder
* Inside the swift folder, go to ``share/qss``
* Open ``fonts.mac.qss`` inside a text editor
* Delete the ``line: font-family: "Arial";``
* Start swiftgui

We will fix this (likely together with #106) soon.

**Comment by nola504-4now** [comment]
Thank you Lars. It is working now.  I tried Discord but I was having trouble creating an account.  Can you please explain when to use Github vs. Discord for support issues?

**Comment by ltoenning** [comment]
> Can you please explain when to use Github vs. Discord for support issues?

There is no clear line. But in general, GitHub issues should be used if something is broken or for feature requests. Discord is mainly used for user support.
