### ISSUE TITLE
Error loading xswiftbus plugin

### ISSUE THREAD

**Issue by albertczyk** [swift-project/pilotclient#83]
After updating to 0.9.5.131, xswiftbus plugin fails to load with this message in log.txt:
 Error Code = 127 : The specified procedure could not be found.
Obviously, swift client cannot connect and shows an error message.

This is in XPlane 10.51r2.

After downgrading (only the X-Plane plugin) to 0.9.4.389 it works fine again despite the version mismatch warning, and the error doesn't appear.

**Comment by oktal3700** [comment]
X-Plane 10 is no longer supported in swift 0.9.5. Sorry about that. With the addition of support for the Vulkan renderer of X-Plane 11, it would have been too much effort for us to maintain support for both.

**Comment by albertczyk** [comment]
OK, thanks for your answer! Time to upgrade then...
