### ISSUE TITLE
ATC flightplan and 3-letter airport codes

### ISSUE THREAD

**Issue by FlyingFoxVATSIM** [swift-project/pilotclient#89]
Some airports do not have ICAO identifiers, but 3-letter FAA codes, e.g. 3Z1 Feather River, 4KA Tununak, 5QC Quartz Creek Kougarok, WBB Stebbins, SVS Stevens Village, 5Z5 Kantishna

When filling in a FPL in swiftGUI these codes go well through the validation process, but when sending such FPLs to VATSIM they do not get uploaded/accepted. I have tried it several times today after a user reported this issue.

In principle, the VATSIM-system does accept those codes well, I tried it via the flightplan pre-filing form.

**Comment by oktal3700** [comment]
I tried with 1B2 Katama and it is working. If it is still not working for you then I will be very confused.
