### ISSUE TITLE
Tower View

### ISSUE THREAD

**Issue by NewoIsTaken** [swift-project/pilotclient#98]
Hey,

Is it possible for tower view to be added to Swift?

Thanks,
Newo

**Comment by FlyingFoxVATSIM** [comment]
> 
> 
> Hey,
> 
> Is it possible for tower view to be added to Swift?
> 
> Thanks,
> Newo

swift can be used for tower view in Euroscope and vSTARS, or are you asking for something more specific?

[](https://docs.swift-project.org/doku.php?id=tower_view_controllers_euroscope_vstars)

**Comment by NewoIsTaken** [comment]
Oh, OK. I didn't see that article. Thanks!
